# Generated by Django 3.2 on 2021-06-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('testName', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('questionPaper', models.FileField(upload_to='')),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userEmail', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('marks', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tester.test')),
            ],
        ),
        migrations.CreateModel(
            name='CreatedTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tester.test')),
                ('userEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tester.user')),
            ],
            options={
                'unique_together': {('userEmail', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CompletedTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksObtained', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tester.test')),
                ('userEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tester.user')),
            ],
            options={
                'unique_together': {('userEmail', 'code')},
            },
        ),
    ]
