# Generated by Django 3.2 on 2021-05-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
