# Generated by Django 3.2 on 2021-06-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0002_auto_20210531_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_access_code', models.IntegerField(primary_key=True, serialize=False)),
                ('testName', models.CharField(max_length=50)),
                ('questionPaper', models.FileField(upload_to='')),
            ],
        ),
    ]
