# Generated by Django 3.2 on 2021-06-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
