# Generated by Django 3.2 on 2021-06-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0004_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_access_code', models.IntegerField(primary_key=True, serialize=False)),
                ('testName', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('questionPaper', models.FileField(upload_to='')),
            ],
        ),
    ]
