# Generated by Django 3.2 on 2021-06-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0005_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_access_code',
            new_name='code',
        ),
    ]
