# Generated by Django 3.2 on 2021-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0007_completedtests_createdtests_joinedtests'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtests',
            name='marksObtained',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JoinedTests',
        ),
    ]
