# Generated by Django 3.2 on 2021-06-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0008_auto_20210605_1843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedtests',
            unique_together={('userEmail', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='createdtests',
            unique_together={('userEmail', 'code')},
        ),
    ]
